version: 2.1

setup: true

orbs:
  path-filtering: gendosu/path-filtering-orb@dev:first

jobs:
  generate-config:
    docker:
      - image: bufferings/cimg-cue
    steps:
      - checkout
      - run:
          name: Generate config list
          command: |
            find . -type f -regex '.*/\.circleci/.*\.yml' -not -regex '\./\.circleci/config\.yml' \
            | tee .circleci/config-list.txt
      - run:
          name: Generate config
          command: |
            cat .circleci/config-list.txt \
            | awk '{printf "\"%s\" ", $0}' \
            | xargs -0 -I {} sh -c 'cue export {} --out yaml' \
            | tee .circleci/generated_config.yml
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/generated_config.yml

workflows:
  setup-workflow:
    jobs:
      - generate-config
      - path-filtering/filter:
          workspace_path: .
          config-path: .circleci/generated_config.yml
          mapping: |
            service1/.* build-service1 true
            service2/.* build-service2 true
          requires:
            - generate-config
