version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
#   path-filtering: gendosu/path-filtering-orb@dev:first

jobs:
  generate-config:
    docker:
      - image: bufferings/cimg-cue
    steps:
      - checkout
      - run:
          name: setenv
          command: |
            export GENTESTENV=gentestvalue
      - run:
          name: Generate conditions
          command: |
            set +e
            mkdir -p /tmp/.circleci
            git diff --name-only origin/main origin/<< pipeline.git.branch >> | tee /tmp/.circleci/diff.log
            export SERVICE1=`grep "^service1/.*.txt" /tmp/.circleci/diff.log | wc -l && true`
            export SERVICE2=`grep "^service2/.*.txt" /tmp/.circleci/diff.log | wc -l && true`
            echo "{ \"build-service1\": $SERVICE1, \"build-service2\": $SERVICE2 }" >> /tmp/.circleci/parameters.json
            exit 0
      - run:
          name: Generate config list
          command: |
            find . -type f -regex '.*/\.circleci/.*\.yml' -not -regex '\./\.circleci/config\.yml' \
            | tee .circleci/config-list.txt
      - run:
          name: Generate config
          command: |
            cat .circleci/config-list.txt \
            | awk '{printf "\"%s\" ", $0}' \
            | xargs -0 -I {} sh -c 'cue export {} --out yaml' \
            | tee .circleci/generated_config.yml
      - persist_to_workspace:
          root: /tmp
          paths:
            - .circleci
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
          parameters: /tmp/.circleci/parameters.json

workflows:
  setup-workflow:
    jobs:
      - generate-config
